### ISSUE TITLE
Bump version to 2.6.0 and release oxygen cut

### ISSUE THREAD

**Issue by hazendaz** [revelc/jsdt-core#2]
@ctubbsii 

eclipse jsdt version is as follows: org.eclipse.wst.jsdt.core\2.0.300.v201703171536

Trying to match up with eclipse version would be a somewhat difficult thing to do given we are ahead and we are building from core distro so we would also potentially be ahead of what they released to central.  So sticking to what we have is probably fine for time being.  Bumping minor version on this should be good enough.  Please give me a go ahead and I'll take care of this.

**Comment by ctubbsii** [comment]
Go right ahead. Let me know if you have trouble releasing with the changes I made to the release plugins.

The main difference is that the `release:prepare` goal doesn't actually build the project... it just bumps versions, and does some extra git commits, so that the manifest versions are bumped to match the POM version.

If you have your gpg-agent pre-loaded with your gpg key, you shouldn't have to do much more than `mvn release:prepare && mvn release:perform` to push things out to the Nexus staging repo. After that, it's a simple matter of closing/releasing the staging repo and pushing up the commits and tag.

One thing I do is replace the tag generated from `release:prepare` with a gpg-signed tag, but that's optional. I just like seing GitHub show a tag as "Verified".

**Comment by hazendaz** [comment]
@ctubbsii All went well but what was different is that it did not directly commit to the upstream (ie here).  I assume you turned that off in favor of using the fork only then pull request over.  I have not looked to confirm but wanted to make note of that.  I like it that way actually as it keeps the workflow of pull requests in place for everything assuming that was intended.

**Comment by ctubbsii** [comment]
@hazendaz `pushChanges` in the release plugin is set to `false` for the reasons specified in https://github.com/revelc/formatter-maven-plugin/issues/255#issuecomment-340315755

You can do a PR if you like, or you can just push once you're satisfied that the commits are correct. I don't see much point in reviewing PRs for auto-generated commits, but there may be some value in letting the CI tools build in the PR before releasing the staging repo at Sonatype's OSS Nexus server.
